# Generated by Django 2.0 on 2017-12-12 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMB', 'Combustão'), ('ELET', 'Elétrico')], default='COMB', max_length=4)),
                ('placa', models.CharField(max_length=10)),
                ('cor', models.CharField(blank=True, default='', max_length=15)),
                ('modelo', models.TextField()),
                ('ano', models.CharField(max_length=10)),
                ('chassi', models.CharField(max_length=25)),
                ('capacidade', models.CharField(max_length=5)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('user_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_cad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
