# Generated by Django 2.0 on 2017-12-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20171212_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
