# Generated by Django 2.0 on 2017-12-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20171212_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
