# Generated by Django 2.0 on 2017-12-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20171212_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especial',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snippets.Veiculo')),
                ('potencia_motor', models.PositiveSmallIntegerField()),
                ('zero_100_seg', models.FloatField()),
                ('vel_maxima', models.PositiveSmallIntegerField()),
                ('nv_conforto', models.PositiveSmallIntegerField()),
            ],
            bases=('snippets.veiculo',),
        ),
    ]
