# Generated by Django 2.0 on 2017-12-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especial',
            name='nv_conforto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='especial',
            name='potencia_motor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='especial',
            name='vel_maxima',
            field=models.FloatField(),
        ),
    ]
