# Generated by Django 2.0 on 2017-12-12 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0008_auto_20171212_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('FIS', 'Física'), ('JUR', 'Jurídica')], default='FIS', max_length=3)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('nome', models.CharField(max_length=70)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('dt_nascimento', models.DateTimeField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('user_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_us_cad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='user_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_us_cad', to=settings.AUTH_USER_MODEL),
        ),
    ]
