# Generated by Django 2.0 on 2017-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20171212_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dt_nascimento',
            field=models.DateField(),
        ),
    ]
