# Generated by Django 2.0 on 2017-12-12 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0010_auto_20171212_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPrecos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('user_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_precos_us_cad', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_precos_veiculo', to='snippets.Veiculo')),
            ],
            options={
                'ordering': ('data_cadastro',),
            },
        ),
    ]
