# Generated by Django 2.0 on 2017-12-13 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0012_aluguel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ocorrencia', models.DateTimeField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_coberto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistro_cliente', to='snippets.Cliente')),
                ('user_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistro_us_cad', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistro_veiculo', to='snippets.Veiculo')),
            ],
            options={
                'ordering': ('data_cadastro',),
            },
        ),
    ]
